feat/comment-space
fourmolu/fourmolu pull request #120
Opened 2021-10-14 04:44 UTC by dmarticus

my attempt at resolving the issue I filed: #118

2021-10-14 16:17 UTC, dmarticus commented on app/Main.hs
> +-- --------------------------------------------------------------------------
oh ooops, my change caused this!  Let me make an exception to `---` characters, lol.

2021-10-18 16:56 UTC, dmarticus commented on fourmolu.cabal
> +
oh, that's my bad.  Definitely was an accident that I didn't catch when self-reviewing.  I'll remove it!

2021-10-18 17:16 UTC, georgefst commented
> My only concern is, how does Ormolu handle this? My gut reaction is that Ormolu has the same behavior, in which case, this should be fixed in Ormolu and then ported to Fourmolu by the usual process.

In general I agree. And I think we should have some guidance (probably in the form of an issue template) about considering asking a question upstream first. In this case it isn't a bug as such and it's possible that Tweag wouldn't want to "fix" it. But there's little harm in asking.

2021-10-18 17:19 UTC, georgefst requested changes
Needs at least one test involving Haddock comments. I worry that `--|comment` -> `-- | comment` is an AST change.

2021-10-20 12:24 UTC, georgefst commented
> cool, ormolu merged in my changes with this PR [tweag/ormolu#809](https://github.com/tweag/ormolu/pull/809)
> 
> @georgefst, should we just upstream those changes here, or do you want me to make a separate PR that puts the rule behind a flag?

Cool! In that case I'm happy to just merge Ormolu as-is, and wait til someone complains about wanting to switch the behaviour off.

This should hopefully be a very simple merge. We have some guidance here: https://github.com/fourmolu/fourmolu/blob/master/DEVELOPER.md#merging-upstream. But if you don't want to bother going through that, one of us will get round to it eventually, probably when the next version of Ormolu is released.

Are you happy to wait a while for an actual release? We've never previously published stuff from Ormolu before they have, and I'd be wary of doing so.

2021-10-30 14:06 UTC, georgefst commented
Implemented upstream. Feel free to subscribe to #126.

2021-10-30 14:06 UTC, closed without merging

2021-11-02 16:36 UTC, dmarticus commented
Hi @georgefst, sorry for all the questions, but what does 
> subscribe to #126
mean in this context?  Are you saying that once y'all merge in Ormolu's latest changes to Fourmolu and release it, my feature that I merged to Ormolu will be released for Fourmolu as well?