Support automatic line breaking at column limit
fourmolu/fourmolu pull request #305
Opened 2023-03-26 20:14 UTC by CrystalSplitter

This is a revival of the work done in #102 by @gustavoavena

This feature is implemented as a hack, as described by @georgefst in Issue #71.

This breaks idempotency, which is an unfortunate limitation of this implementation. Open to making fixes for idempotency, but from the comments in #71, this seems to be okay given the utility and the warning.

2023-03-26 20:27 UTC, brandonchinn178 requested changes

2023-03-26 20:27 UTC, brandonchinn178 commented on data/examples/declaration/rewrite-rule/prelude1-line-break-out.hs
Add new tests to `data/fourmolu/` instead, to easily track which tests were added by us and which tests are represented upstream

2023-03-26 20:27 UTC, brandonchinn178 commented on src/Ormolu/Config/Gen.hs
Did you edit this file manually? As mentioned at the top of this file, this file is autogenerated. Please follow the instructions in `DEVELOPER.md` under the section "Adding a new configuration option"

2023-03-26 20:27 UTC, brandonchinn178 commented on tests/Ormolu/PrinterSpec.hs
I don't think this file needs to/should change. All the files in `data/` should be formatted with Ormolu's format or Fourmolu's default format.

2023-03-26 20:27 UTC, brandonchinn178 commented on README.md
> +column-limit: no-limit
Nit: can we make the `NoLimit` option `column-limit: none`? Reads a little better / less redundant to me.

2023-03-26 20:50 UTC, CrystalSplitter commented on data/examples/declaration/rewrite-rule/prelude1-line-break-out.hs
Can do!

2023-03-26 20:50 UTC, CrystalSplitter commented on src/Ormolu/Config/Gen.hs
Almost all the code here is rebased and tweaked code from #102 with line-by-line fixes to get everything to work, rather than a complete reimplementation of the work.

I'll scrap the changes to this file and redo them.

2023-03-26 20:50 UTC, CrystalSplitter commented on tests/Ormolu/PrinterSpec.hs
Is there a way to specify tests for alternative configs? We're not modifying the default behaviour, but it would still be nice to have tests for this. Otherwise there's no reason to add new tests--no behaviour would be changing.

2023-03-26 20:50 UTC, CrystalSplitter commented on README.md
> +column-limit: no-limit
Sure, pretty easy fix!

2023-03-26 20:51 UTC, brandonchinn178 commented on tests/Ormolu/PrinterSpec.hs
Yes, following the instructions in `DEVELOPER.md` goes through all of that

2023-03-27 02:44 UTC, CrystalSplitter commented on src/Ormolu/Config/Gen.hs
Done!

2023-03-27 02:44 UTC, CrystalSplitter commented on data/examples/declaration/rewrite-rule/prelude1-line-break-out.hs
Done!

2023-03-27 02:45 UTC, CrystalSplitter commented on tests/Ormolu/PrinterSpec.hs
Done, though I still had to make some modifications to how we run `TestGroup`s.

2023-03-27 02:45 UTC, CrystalSplitter commented on README.md
> +column-limit: no-limit
Done!

2023-03-27 02:59 UTC, brandonchinn178 approved these changes
Small nits, let me know if you agree, or I can merge as-is

2023-03-27 02:59 UTC, brandonchinn178 commented on data/fourmolu/column-limit/input.hs
> +-- ----------------  Know limitation: idempotence is broken ----------------
```suggestion
-- ----------------  Known limitation: idempotence is broken ----------------
```

2023-03-27 02:59 UTC, brandonchinn178 commented on src/Ormolu/Config/Gen.hs
> +          case (readEither other :: Either String Int) of
Nit: does this require the explicit type annotation? Can we remove it?

2023-03-27 02:59 UTC, brandonchinn178 commented on tests/Ormolu/Config/PrinterOptsSpec.hs
> +          testCaseSuffix = suffix1,
Nit: Would be great to avoid spaces in the filename. Thoughts on `output-limit=none.hs` + `output-limit=100.hs`?

2023-03-27 03:06 UTC, CrystalSplitter commented on src/Ormolu/Config/Gen.hs
> +          case (readEither other :: Either String Int) of
This was leftover from some type debugging. Thanks for the catch. We can remove it.

2023-03-27 03:11 UTC, CrystalSplitter commented on tests/Ormolu/Config/PrinterOptsSpec.hs
> +          testCaseSuffix = suffix1,
Yeah, I don't like space either. Personally somewhat hesitant on `=`, since that'll also need escaping in many shells.

Any opinions on:

* `output-limit-none.hs`/`output-limit-100.hs`?
* `output-limit-eq-none.hs`/`output-limit-eq-100.hs`?

I favour the first, but anything that doesn't need escaping is good to me.

2023-03-27 03:12 UTC, CrystalSplitter commented on tests/Ormolu/Config/PrinterOptsSpec.hs
> +          testCaseSuffix = suffix1,
Ah, I see that the `=` is already common practice in `respectful-module-where`. I can do that.

2023-03-27 03:18 UTC, brandonchinn178 commented on tests/Ormolu/Config/PrinterOptsSpec.hs
> +          testCaseSuffix = suffix1,
oh feel free to not use `=`. Just out of curiostiy, what escaping issues are there? I don't think there'd be an issue with the variable assignment `=`.

Of the two options you listed, I like the non-`eq` one

2023-03-27 03:41 UTC, CrystalSplitter commented on tests/Ormolu/Config/PrinterOptsSpec.hs
> +          testCaseSuffix = suffix1,
> I don't think there'd be an issue with the variable assignment =.

I can only think really think of a variable assignment issue if you're trying to execute a command which contains `=` in the name. e.g.

```bash
# Bash/ZSH
$ echo 'echo RAN' > ~/bin/hello=world && chmod u+x ~/bin/hello=world
$ hello=world  # Variable assignment silence
$ 'hello=world'  # Actually executing it
RAN
```

That's not the case here, but it's always something I'm a little wary of. The other thing that comes to mind is the autocomplete will insert `\` prior to the filenames, but that's more an annoyance than anything actually an issue.

There are also commands come to mind which use `=` for opt assignment in shell commands (particularly ones that don't lead with `-`). This can cause confusion as to whether it's a opt or a filename. Some Golang programs I've worked with do that, but I think that's a _really_ niche case.

---

I've already implemented the `=` filename version, which I think is probably fine?

2023-03-27 03:51 UTC, CrystalSplitter commented on src/Ormolu/Config/Gen.hs
> +          case (readEither other :: Either String Int) of
Done.

2023-03-27 03:51 UTC, CrystalSplitter commented on data/fourmolu/column-limit/input.hs
> +-- ----------------  Know limitation: idempotence is broken ----------------
Had to regenerate. Done.

2023-03-27 03:52 UTC, CrystalSplitter commented on tests/Ormolu/Config/PrinterOptsSpec.hs
> +          testCaseSuffix = suffix1,
Done with `=`.

2023-03-27 03:56 UTC, brandonchinn178 approved these changes
One last nit. Feel free to ignore.

2023-03-27 03:56 UTC, brandonchinn178 commented on src/Ormolu/Config/Gen.hs
> +            (Right otherInt) -> Right . ColumnLimit $ otherInt
Nit: didn't catch this earlier, but this could also be

```hs
case s of
  "none" -> ...
  _ | Just x <- readMaybe s -> ...
  _ -> ...
```

2023-03-27 04:15 UTC, CrystalSplitter commented on src/Ormolu/Config/Gen.hs
> +            (Right otherInt) -> Right . ColumnLimit $ otherInt
Done. Had to modify the import list (`readMaybe` wasn't available).

2023-03-27 04:17 UTC, CrystalSplitter commented
Hold on, parsing issue.

> Error in $['column-limit']: parsing ColumnLimit failed, expected String, but encountered Number.

Maybe have broken it up somewhere in my fixups...

2023-03-27 04:36 UTC, brandonchinn178 commented
@CrystalSplitter the adtParseJson implementation, I think.

Also, the tests apparently dont test that function... I'll have to think about how best to test it

2023-03-27 04:41 UTC, CrystalSplitter commented
The underlying issue here is that column limit can both be a `String` (`none`) and an `Int` during parsing.

Some solutions:

* A real quick solution to this would be that 0 or lower is `none`. This is originally what it did at the very beginning, but it was requested that Gustavo change that. I think this option is fine, though weird from a user perspective.
* Another solution is make a somewhat hacky parser that returns both the string `"none"` and an integer as a raw string. This is fine from a user perspective but weird for implementation.
* And another solution is to write in the documentation that the integer has to be wrapped in quotes. I dislike this option.

2023-03-27 04:47 UTC, brandonchinn178 commented
Or just parse it directly?

```hs
parseJson = \case
  String "none" -> pure NoLimit
  Number x | Right i <- floatingOrIntegral x -> pure $ ColumnLimit i
  _ -> fail "Invalid ColumnLimit"
```

It'll slightly duplicate the adtParseText implementation, which I think is fine.

2023-03-27 05:30 UTC, CrystalSplitter commented
Done, but I had to include `scientific` in the depends. I noticed that there was a test that broke with that, so I patched that as well. I'm unsure if that was the right move, though.

2023-03-28 00:59 UTC, merged